
package emr.services.person;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "emrPersonService", targetNamespace = "http://person.services.emr", wsdlLocation = "http://zim:9090//EMR_thesis_project/emrPersonService?wsdl")
public class EmrPersonService
    extends Service
{

    private final static URL EMRPERSONSERVICE_WSDL_LOCATION;
    private final static WebServiceException EMRPERSONSERVICE_EXCEPTION;
    private final static QName EMRPERSONSERVICE_QNAME = new QName("http://person.services.emr", "emrPersonService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://zim:9090//EMR_thesis_project/emrPersonService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMRPERSONSERVICE_WSDL_LOCATION = url;
        EMRPERSONSERVICE_EXCEPTION = e;
    }

    public EmrPersonService() {
        super(__getWsdlLocation(), EMRPERSONSERVICE_QNAME);
    }

    public EmrPersonService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EMRPERSONSERVICE_QNAME, features);
    }

    public EmrPersonService(URL wsdlLocation) {
        super(wsdlLocation, EMRPERSONSERVICE_QNAME);
    }

    public EmrPersonService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EMRPERSONSERVICE_QNAME, features);
    }

    public EmrPersonService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmrPersonService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EmrPerson
     */
    @WebEndpoint(name = "emrPersonServicePort")
    public EmrPerson getEmrPersonServicePort() {
        return super.getPort(new QName("http://person.services.emr", "emrPersonServicePort"), EmrPerson.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmrPerson
     */
    @WebEndpoint(name = "emrPersonServicePort")
    public EmrPerson getEmrPersonServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://person.services.emr", "emrPersonServicePort"), EmrPerson.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMRPERSONSERVICE_EXCEPTION!= null) {
            throw EMRPERSONSERVICE_EXCEPTION;
        }
        return EMRPERSONSERVICE_WSDL_LOCATION;
    }

}
